name: Run Bash Script on Mac OS
on: [push]
jobs:
  Run-Script:
    runs-on: macos-12
    steps:
      - name: Remove Xcode
        run: sudo rm -rf /Applications/Xcode_14.2.app/
      - name: Delete Xcode in '/' directory
        run: sudo rm -rf /Library/Developer/
      # Not needed to remove Xcode, will leave here for now in case is needed
      # - name: Remove other Xcode support files in the Library cache folder
      #   run: sudo rm -rf ~/Library/Caches/com.apple.dt.Xcode
      - name: Reset the default command-line tools
        run: sudo xcode-select -r
      - name: Check whether Xcode is still installed
        run: |
          if xcode-select -p ; then
            echo "Xcode is installed"
          else
            echo "Xcode is not installed"
          fi

      # - name: See if Xcode Command Line Tools is installed where expected
      #   run: ls -la /Library/Developer/CommandLineTools
      # - name: Try to get rid of just the Xcode Command Line Tools only
      #   run: sudo rm -rf /Library/Developer/CommandLineTools
      # - name: Reset the default command-line tools
      #   run: sudo xcode-select -r
      # - name: Check if Xcode Command Line Tools is still installed
      #   run: xcode-select -p


      # Might have to do this as well - see if you need it: You also need to reset the default command-line tools by entering this command "sudo xcode-select -r"

      #   # Homebrew is pre-installed on the GitHub Actions MacOS Runner (Virtual Machine) - see: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#:~:text=Composer%202.5.5-,Homebrew%204.0.15,-Miniconda%2023.3.1
      #   # - So we need to remove it
      #   # Uninstalling Homebrew using the following command recommended in the docs doesn't fail, but doesn't remove everything it should do due to not having sudo permissions:
      #   # NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
      #   # - So we need to use sudo to run it
      # - name: Uninstall pre-installed Homebrew version
      #   run: |
      #     curl -sLO https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh
      #     chmod +x ./uninstall.sh
      #     sudo ./uninstall.sh --force
      # - name: Remove remaining pre-installed Homebrew directories that weren't removed
      #   # The Homebrew output tells us that these files possibly related to Homebrew on the GitHub Actions MacOS Runner haven't been deleted, so we should remove them:
      #   run: |
      #     sudo rm -rf /usr/local/.com.apple.installer.keep
      #     sudo rm -rf /usr/local/Frameworks/
      #     sudo rm -rf /usr/local/Homebrew/
      #     sudo rm -rf /usr/local/aws-cli/
      #     sudo rm -rf /usr/local/bin/
      #     sudo rm -rf /usr/local/etc/
      #     sudo rm -rf /usr/local/include/
      #     sudo rm -rf /usr/local/lib/
      #     sudo rm -rf /usr/local/microsoft/
      #     sudo rm -rf /usr/local/miniconda/
      #     sudo rm -rf /usr/local/opt/
      #     sudo rm -rf /usr/local/sbin/
      #     sudo rm -rf /usr/local/sessionmanagerplugin/
      #     sudo rm -rf /usr/local/share/
      #     sudo rm -rf /usr/local/var/
      # - name: Ensure reportedly deleted pre-installed Homebrew directories no longer exist
      #   # The Homebrew output tells us that these should have been deleted, but we should make sure that they are definitely removed:
      #   run: |
      #     sudo rm -rf /usr/local/Caskroom
      #     sudo rm -rf /usr/local/bin/brew
      # - name: Ensure pre-installed Homebrew version has been removed
      #   # Check if Homebrew is installed using `command -v brew`. If Homebrew is not already installed, this command will not print anything to standard error or standard output.
      #   # If Homebrew is already installed (if anything is printed to standard error or standard output), print a message stating that the GitHub Workflow needs to be changed to ensure that Homebrew is not already installed on the macOS virtual machine, and fail the GitHub Workflow.
      #   run: |
      #     if command -v brew &> /dev/null
      #       then echo 'Homebrew is still installed but it should have been removed. Uninstall Homebrew to ensure that the bash script does not try to install Homebrew for a second time.'
      #       exit 1
      #     fi
      # # # They do exist - it prints out: /Applications/Xcode_14.2.app/Contents/Developer
      # # - name: Check if Xcode Command Line Tools are installed
      # #   run: xcode-select -p
      # # # Failed: --remove isn't a valid flag
      # # # See: https://github.com/BenRoss92/automate-new-laptop-setup/actions/runs/5078886532/jobs/9123951223#step:7:1
      # # - name: Remove Xcode Command Line Tools
      # #   run: xcode-select --remove
      # # # Didn't get this far:
      # # - name: Re-check if Xcode Command Line Tools are installed
      # #   run: xcode-select -p
      # # - name: Check if Xcode Command Line Tools are installed
      # #   run: xcode-select -p
      # # - name: Remove Xcode Command Line Tools
      # #   run: sudo rm -rf /Applications/Xcode_14.2.app
      # #   # Re-check is still passing but should be failing - is printing: /Applications/Xcode_14.2.app/Contents/Developer - but should be failing
      # #   # See https://github.com/BenRoss92/automate-new-laptop-setup/actions/runs/5079110397/jobs/9124445320
      # # - name: Re-check if Xcode Command Line Tools are installed
      # #   run: xcode-select -p

      # - name: Check if Xcode Command Line Tools are installed
      #   run: xcode-select -p
      # - name: Remove Xcode Command Line Tools
      #   run: sudo rm -rf /Applications/Xcode_14.2.app
      # - name: See if /Applications/Xcode_14.2.app still exists
      #   run: ls -la /Applications/Xcode_14.2.app
      # - name: 
      #   run: sudo xcode-select -r
      # - name: Re-check if Xcode Command Line Tools are installed
      #   run: xcode-select -p
      # - uses: actions/checkout@v3
      # - name: Run bash script
      #   run: ./set-up-laptop.sh