name: Run Bash Script on Mac OS
on: [push]
jobs:
  Run-Script:
    runs-on: macos-12
    steps:
    ## Try to run your bash script in the macos-12 environment
      ## WORKS: Clone your repository code (including the bash script) onto the runner
      # - uses: actions/checkout@v3
      ## WORKS: Try to run the bash script inside of the runner
      # - name: Run bash script
      #   run: ./set-up-laptop.sh
      ## CONFIRMED: Homebrew is already installed inside the runner:
      # - name: Check if Homebrew comes pre-installed on GitHub Actions MacOS Virtual Machine
      #   run: brew help
      ## Uninstall Homebrew (pre-installed on GitHub Actions MacOS Virtual Machine):
      ## - Doesn't fail, but doesn't remove everything it should due to not having sudo permissions
      # - name: Uninstall pre-installed Homebrew version
        # run: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
      - name: Uninstall pre-installed Homebrew version
        run: |
          curl -sLO https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh
          chmod +x ./uninstall.sh
          sudo ./uninstall.sh --force
      - name: Remove remaining pre-installed Homebrew directories
        run: |
          sudo rm -rf /usr/local/Homebrew
          sudo rm -rf /usr/local/Caskroom
          sudo rm -rf /usr/local/bin/brew
